FROM alpine
LABEL "io.containers.capabilities"="CHOWN,DAC_OVERRIDE,FOWNER,FSETID,KILL,NET_BIND_SERVICE,SETFCAP,SETGID,SETPCAP,SETUID,SYS_CHROOT"

RUN set -xeuf; \
  apk add --no-cache buildah fuse-overlayfs; \
  adduser -D build; \
  echo -e "build:1:999\nbuild:1001:64535" > /etc/subuid; \
  echo -e "build:1:999\nbuild:1001:64535" > /etc/subgid; \
  :

COPY storage.conf containers.conf /etc/containers/

USER build

ENV BUILDAH_ISOLATION=chroot HOME=/home/build USER=build LOGNAME=build
