FROM golang:1.24-alpine
RUN go install github.com/a-h/templ/cmd/templ@latest
RUN go install github.com/a-h/templ/cmd/templ-tailwindcss@latest
RUN curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
RUN chmod +x tailwindcss-linux-x64
RUN mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss
